[server]
name = "redmud"
ip_addr = "127.0.0.1"
ports = [3389]

[log]
file = "redmud.log"
level = "debug"

[database]
user = "redmud"
password = "redmud"
url = "localhost"
db_name = "redmud"
db_version = "10"

# Map name(s) and format(s)
# Admins?
# Character encodings? (ascii vs utf-8)
# Text color handling?
# Resource limits? (can these be found within the program, too?)
# Modules/Extensions?

# External dependencies & tools
# export PGDATABASE=redmud
# cargo install diesel_cli --no-default-features --features postgres
